const DATA={
 WISDM:{positive:.5715,negative:.5805,time:'~10 min',note:'Varies by activity; Downstairs succeeds earliest.',thresholds:{Downstairs:.5,Jogging:1,Sitting:3,Upstairs:3,Standing:4,Walking:4}},
 MotionSense:{positive:.6009,negative:.6315,time:'~5 min',note:'All activities succeed at ε = 1.',thresholds:{Downstairs:1,Jogging:1,Sitting:1,Upstairs:1,Standing:1,Walking:1}},
 HHAR:{positive:.5769,negative:.5896,time:'~5 min',note:'All activities succeed at ε = 1.',thresholds:{Downstairs:1,Jogging:1,Sitting:1,Upstairs:1,Standing:1,Walking:1}},
 WESAD:{positive:.7956,negative:.8099,time:'~3 min',note:'Physiological embeddings are highly sensitive.',thresholds:{Stress:1,'Non-stress':1}}
};
let current='WISDM';
const tabs=document.getElementById('tabs'),eps=document.getElementById('eps'),canvas=document.getElementById('chart'),ctx=canvas.getContext('2d');
Object.keys(DATA).forEach(k=>{const b=document.createElement('button');b.className='tab'+(k===current?' active':'');b.textContent=k;b.onclick=()=>{current=k;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');update();};tabs.appendChild(b)});
function estimate(d,e){const minThr=Math.min(...Object.values(d.thresholds));const success=e>=minThr;let sim=Math.max(-.35,d.positive-(e/(minThr+3))*0.22-(success?0.10:0));let loss=Math.min(1.35,1-sim);if(current==='WESAD'){sim=e===0?.84:Math.max(-.30,.83-e*.12);loss=1-sim}return{sim,loss,success};}
function update(){const d=DATA[current],e=parseFloat(eps.value),est=estimate(d,e);document.getElementById('datasetTitle').textContent=current;document.getElementById('epsVal').textContent=e;document.getElementById('simOut').textContent=est.sim.toFixed(3);document.getElementById('lossOut').textContent=est.loss.toFixed(3);document.getElementById('statusOut').textContent=est.success?'Success':'Fail';document.getElementById('statList').innerHTML=`<div class="pill"><span>Positive pair similarity</span><strong>${d.positive}</strong></div><div class="pill"><span>Negative pair similarity</span><strong>${d.negative}</strong></div><div class="pill"><span>Execution time</span><strong>${d.time}</strong></div><div class="pill"><span>Summary</span><strong>${d.note}</strong></div>`;drawChart(d,e)}
function drawChart(d,e){ctx.clearRect(0,0,canvas.width,canvas.height);const W=canvas.width,H=canvas.height,p=58;ctx.font='15px Inter,Arial';ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=1;for(let i=0;i<=5;i++){const y=p+(H-2*p)*i/5;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(W-p,y);ctx.stroke();ctx.fillStyle='rgba(238,244,255,.55)';ctx.fillText((1-i/5).toFixed(1),18,y+4)}ctx.fillStyle='rgba(238,244,255,.8)';ctx.fillText('Epsilon vs similarity/loss',p,28);let xs=[0,1,2,3,4,5,6,8,10];function x(v){return p+(W-2*p)*v/10}function y(v){return H-p-(H-2*p)*Math.max(0,Math.min(1,v))}function line(vals,color){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{i?ctx.lineTo(x(xs[i]),y(v)):ctx.moveTo(x(xs[i]),y(v))});ctx.stroke();vals.forEach((v,i)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x(xs[i]),y(v),4,0,Math.PI*2);ctx.fill()})}const simVals=xs.map(v=>estimate(d,v).sim);const lossVals=xs.map(v=>estimate(d,v).loss);line(simVals,'#6ee7ff');line(lossVals,'#fb7185');ctx.fillStyle='#6ee7ff';ctx.fillText('Adversarial similarity',W-250,42);ctx.fillStyle='#fb7185';ctx.fillText('Contrastive loss',W-250,66);ctx.strokeStyle='#fbbf24';ctx.lineWidth=2;ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(x(e),p);ctx.lineTo(x(e),H-p);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fbbf24';ctx.fillText('ε = '+e,x(e)+8,p+18);ctx.fillStyle='rgba(238,244,255,.65)';xs.forEach(v=>ctx.fillText(v,x(v)-5,H-20));ctx.fillText('ε',W-35,H-20)}
eps.addEventListener('input',update);update();
